name: trip
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.2
  english_words: ^3.1.5
  http: ^0.12.0+2
  common_utils: ^1.1.1
  scoped_model: ^1.0.1
  flutter_map: ^0.6.1+2
  latlong: ^0.6.1


  dio: ^1.0.9
dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
  fonts:
    - family: PingFang
      fonts:
        - asset: fonts/PingFang.ttf
  assets:
    - assets/berlin.mbtiles
    - assets/map/anholt_osmbright/12/2177/
    - assets/map/anholt_osmbright/12/2178/
    - assets/map/anholt_osmbright/12/2179/
    - assets/map/anholt_osmbright/12/2180/
    - assets/map/anholt_osmbright/12/2181/
    - assets/map/anholt_osmbright/13/4354/
    - assets/map/anholt_osmbright/13/4355/
    - assets/map/anholt_osmbright/13/4356/
    - assets/map/anholt_osmbright/13/4357/
    - assets/map/anholt_osmbright/13/4358/
    - assets/map/anholt_osmbright/13/4359/
    - assets/map/anholt_osmbright/13/4360/
    - assets/map/anholt_osmbright/13/4361/
    - assets/map/anholt_osmbright/13/4362/
    - assets/map/anholt_osmbright/13/4363/
    - assets/map/anholt_osmbright/14/8709/
    - assets/map/anholt_osmbright/14/8710/
    - assets/map/anholt_osmbright/14/8711/
    - assets/map/anholt_osmbright/14/8712/
    - assets/map/anholt_osmbright/14/8713/
    - assets/map/anholt_osmbright/14/8714/
    - assets/map/anholt_osmbright/14/8715/
    - assets/map/anholt_osmbright/14/8716/
    - assets/map/anholt_osmbright/14/8717/
    - assets/map/anholt_osmbright/14/8718/
    - assets/map/anholt_osmbright/14/8719/
    - assets/map/anholt_osmbright/14/8720/
    - assets/map/anholt_osmbright/14/8721/
    - assets/map/anholt_osmbright/14/8722/
    - assets/map/anholt_osmbright/14/8723/
    - assets/map/anholt_osmbright/14/8724/
    - assets/map/anholt_osmbright/14/8725/
    - assets/map/anholt_osmbright/14/8726/
    - assets/map/anholt_osmbright/14/8727/
